[package]
name = "xsv"
version = "0.13.0"  #:version
edition = "2021"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = "A high performance CSV command line toolkit."
documentation = "https://burntsushi.net/rustdoc/xsv/"
homepage = "https://github.com/BurntSushi/xsv"
repository = "https://github.com/BurntSushi/xsv"
readme = "README.md"
keywords = ["csv", "tsv", "slice", "command"]
license = "Unlicense/MIT"
autotests = false

[[bin]]
name = "xsv"
test = false
bench = false
doctest = false

[[test]]
name = "tests"

[profile.release]
strip = true
lto = true
opt-level = "z"
codegen-units = 1

[profile.test]
opt-level = 3

[dependencies]
byteorder = "1"
crossbeam-channel = "0.5"
csv = "1"
csv-index = "0.1.6"
docopt = "1"
filetime = "0.2"
num_cpus = "1.4"
rand = "0.8"
regex = "1"
serde = "1"
serde_derive = "1"
streaming-stats = "0.2"
tabwriter = "1"
threadpool = "1.8"

[dev-dependencies]
quickcheck = { version = "1", default-features = false }
log = "0.4"
